### ISSUE TITLE
建议

### ISSUE THREAD

**Issue by sixgodfan** [debuggerx01/docker_gallery_with_manager#4]
谢谢分享！
1.出掉打开跳出来的打赏信息：Purchase a license [$39] to unlock features and support dev!
2.上传目录不要放根目录，可其他新建的目录
3.视频好像不能播放。谢谢

**Comment by debuggerx01** [comment]
1. 其实这个我已经去掉了，切换到[hacked](https://github.com/debuggerx01/docker_gallery_with_manager/tree/hacked)分支就有去除提醒的代码了——没敢放主分支是怕被人投诉
2. 这个可以自定义，我没改是因为我这边这样弄更方便本地管理
3. 这个项目里只用了ffmpeg去为视频文件生成缩略图，并没有涉及转码操作，播放的时候是直接把原始视频地址交给\<video\>标签，所以视频能不能播放取决于视频格式是否被浏览器支持。我这边自己安卓手机拍摄的mp4视频，都是可以不经转码直接在chrome等浏览器上播放的。
